apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: mqk20zeei-python 
  janus-idp.io/tekton: mqk20zeei-python
  backstage.io/kubernetes-id: mqk20zeei-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: mqk20zeei-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  