apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: mqk20zeei-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: mqk20zeei-python 
  name: mqk20zeei-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: mqk20zeei-python 
